Repository RedHatProductSecurity/osidb, pull requests merged in 2025-08, with the labels that each got.

#1013 [OSIDB-4287] Change package and project manager to uv
  .dockerignore
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  .secrets.baseline
  Dockerfile
  devel-requirements.in
  devel-requirements.txt
  docker-compose.test.yml
  docker-compose.yml
  docs/developer/DEVELOP.md
  mk/checks.mk
  mk/defaults.mk
  mk/setup.mk
  pyproject.toml
  requirements.in
  requirements.txt
  scripts/update_release.sh
  test.Dockerfile
  tox.ini
  uv.lock
Labels: technical

#1021 [OSIDB-4287] Remove dependabot updates
  .github/dependabot.yml
Labels: bug, technical

#1015 Fix logic for available-flaws to match the original spec
  docs/CHANGELOG.md
  openapi.yml
  osidb/api_views.py
  osidb/tests/endpoints/flaws/test_flaws.py
Labels: bug
